from ActiveContourFitting_h import ActiveContourFitting as acf

activeContour = acf(alpha=0.015, beta=10, gamma=0.001, gSigma=1, w_line=-10)
activeContour.getVideo()
activeContour.setInit(n_sides=100, x=210, y=260, height=100, width=100)
activeContour.moreContrast()
activeContour.cropCoef(xCoef=12, yCoef=12)
activeContour.activeContourFitting()
#activeContour.showInitFrame()
#activeContour.showActiveContourFitting()
activeContour.saveActiveContourFitting("Prueba01")
activeContour.saveVideo("Prueba01")

activeContour = acf(alpha=0.015, beta=10, gamma=0.001, gSigma=1, w_line=-20)
activeContour.getVideo()
activeContour.setInit(n_sides=100, x=210, y=260, height=100, width=100)
activeContour.moreContrast()
activeContour.cropCoef(xCoef=12, yCoef=12)
activeContour.activeContourFitting()
#activeContour.showInitFrame()
#activeContour.showActiveContourFitting()
activeContour.saveActiveContourFitting("Prueba02")
activeContour.saveVideo("Prueba02")

activeContour = acf(alpha=0.015, beta=5, gamma=0.001, gSigma=1, w_line=-10)
activeContour.getVideo()
activeContour.setInit(n_sides=100, x=210, y=260, height=100, width=100)
activeContour.moreContrast()
activeContour.cropCoef(xCoef=12, yCoef=12)
activeContour.activeContourFitting()
#activeContour.showInitFrame()
#activeContour.showActiveContourFitting()
activeContour.saveActiveContourFitting("Prueba03")
activeContour.saveVideo("Prueba03")

activeContour = acf(alpha=0.015, beta=10, gamma=0.001, gSigma=1, w_line=-10)
activeContour.getVideo()
activeContour.setInit(n_sides=200, x=210, y=260, height=100, width=100)
activeContour.moreContrast()
activeContour.cropCoef(xCoef=12, yCoef=12)
activeContour.activeContourFitting()
#activeContour.showInitFrame()
#activeContour.showActiveContourFitting()
activeContour.saveActiveContourFitting("Prueba04")
activeContour.saveVideo("Prueba04")

activeContour = acf(alpha=0.015, beta=10, gamma=0.001, gSigma=1, w_line=-20)
activeContour.getVideo()
activeContour.setInit(n_sides=200, x=210, y=260, height=100, width=100)
activeContour.moreContrast()
activeContour.cropCoef(xCoef=12, yCoef=12)
activeContour.activeContourFitting()
#activeContour.showInitFrame()
#activeContour.showActiveContourFitting()
activeContour.saveActiveContourFitting("Prueba05")
activeContour.saveVideo("Prueba05")

activeContour = acf(alpha=0.015, beta=5, gamma=0.001, gSigma=1, w_line=-10)
activeContour.getVideo()
activeContour.setInit(n_sides=200, x=210, y=260, height=100, width=100)
activeContour.moreContrast()
activeContour.cropCoef(xCoef=12, yCoef=12)
activeContour.activeContourFitting()
#activeContour.showInitFrame()
#activeContour.showActiveContourFitting()
activeContour.saveActiveContourFitting("Prueba06")
activeContour.saveVideo("Prueba06")

activeContour = acf(alpha=0.015, beta=10, gamma=0.001, gSigma=1, w_line=-10)
activeContour.getVideo()
activeContour.setInit(n_sides=200, x=210, y=260, height=100, width=100)
activeContour.moreContrast()
activeContour.invertLevels()
activeContour.cropCoef(xCoef=12, yCoef=12)
activeContour.activeContourFitting()
#activeContour.showInitFrame()
#activeContour.showActiveContourFitting()
activeContour.saveActiveContourFitting("Prueba07")
activeContour.saveVideo("Prueba07")

activeContour = acf(alpha=0.015, beta=10, gamma=0.001, gSigma=1, w_line=-20)
activeContour.getVideo()
activeContour.setInit(n_sides=200, x=210, y=260, height=100, width=100)
activeContour.moreContrast()
activeContour.invertLevels()
activeContour.cropCoef(xCoef=12, yCoef=12)
activeContour.activeContourFitting()
#activeContour.showInitFrame()
#activeContour.showActiveContourFitting()
activeContour.saveActiveContourFitting("Prueba08")
activeContour.saveVideo("Prueba08")

activeContour = acf(alpha=0.015, beta=5, gamma=0.001, gSigma=1, w_line=-10)
activeContour.getVideo()
activeContour.setInit(n_sides=200, x=210, y=260, height=100, width=100)
activeContour.moreContrast()
activeContour.invertLevels()
activeContour.cropCoef(xCoef=12, yCoef=12)
activeContour.activeContourFitting()
#activeContour.showInitFrame()
#activeContour.showActiveContourFitting()
activeContour.saveActiveContourFitting("Prueba09")
activeContour.saveVideo("Prueba09")
